# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-24 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(choices=[('province1', 'Province No. 1'), ('province2', 'Province No. 2'), ('province3', 'Province No. 3'), ('province4', 'Gandaki Pradesh'), ('province5', 'Province No. 5'), ('province6', 'Karnali Pradesh'), ('province7', 'Sudurpashchim Pradesh')], max_length=120),
        ),
    ]
