# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20190324_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
