# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_auto_20190316_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(blank=True, to='courses.Course')),
            ],
        ),
    ]
