# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=107.84, max_digits=20),
        ),
    ]
