# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=True),
        ),
    ]
