# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-26 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190326_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_total',
        ),
        migrations.AddField(
            model_name='order',
            name='certificate_total',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=100),
        ),
    ]
