# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='mailchimp_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
